# Vespa container

podman run --name vespa-bigdatabu --hostname vespa-bigdatabu \
  --publish 8080:8080 --publish 19071:19071 \
  vespaengine/vespa

# tensor playground
# https://docs.vespa.ai/playground/#N4KABGBEBmkFxgNrgmUrWQPYAd5QFNIAaFDSPBdDTAO30gGMsAbAExxYEMBPEsmpCIJIAFwK0AzlgBOACgDmEmQWABfAJRxgMrIwDWcAAwA6AIzEcuYyYDsayAIhqBa0hmrlcDIu8GU0JzoGAFsCUS4WFgBLRi5+GkxhKHEpWUVlVU1tXQMbAE5La1MAJgcglww3AU9MbxFfIIp8WvJ6ERCeCMlxBMTCBlTpeSVaFXUtHT1DU1sinBsAZnLEytRqjyb6gb9yANbgkWZ2Tl4AWhCuUUYACz7EoQZJAFcQuWOObh4wACowTu64mIYFGKg0jlWrl2gQe20e0IgzSoQUR7SgH1OPAuV1uZzY4S40RYBDY90EySYrE+vF+-y6XB6RAqUJqWwC8Ka+xRUDRkDCESisS4F3pjLJ5ApLze-MiMTitIBDKBIMy4OZVWhB2w7MaDy5-R5oQJgri2OuNzxBKJJPFSSNArlXAVot66vWKAAuiA1EA

# ColPali demo
# https://huggingface.co/spaces/vespa-engine/colpali-vespa-visual-retrieval
