POST http://localhost:8080/search/
content-type: application/json

{
  "yql": "select * from sources * where {targetHits:10,approximate:true}nearestNeighbor(titledesc_embedding,query_embedding) OR title contains 'jewelry'",
  "ranking.profile": "rrf",
  "query_text": "jewelry",
  "input.query(query_embedding)": "embed(@query_text)",
  "presentation.summary": "titledesc"
}