### add sample docs
POST http://localhost:8080/document/v1/productspace/product/docid/first
content-type: application/json

{
  "fields": {
    "title": "first product",
    "category": "freeware",
    "price": 0
  }
}

### and another one
POST http://localhost:8080/document/v1/productspace/product/docid/2
content-type: application/json

{
  "fields": {
    "title": "second product",
    "category": "expensive",
    "price": 1000
  }
}

### select all
POST http://localhost:8080/search/
content-type: application/json

{
  "yql": "select * from sources * where true"
}

### full-text search
POST http://localhost:8080/search/
content-type: application/json

{
  "yql": "select * from product where title contains 'first'"
}

### boolean logic; exact matches
POST http://localhost:8080/search/
content-type: application/json

{
  "yql": "select * from product where title contains 'first' OR category matches 'expensive'"
}

### shortcut (and performance hack) for an element in a big list

POST http://localhost:8080/search/
content-type: application/json

{
  "yql": "select * from product where category in ('freeware', 'cheap', 'expensive', 'many', 'other', 'terms')"
}

### different rank profile => different score
POST http://localhost:8080/search/
content-type: application/json

{
  "yql": "select * from sources * where title contains 'first'",
  "ranking.profile": "bm25"
}