### add a seller
POST http://localhost:8080/document/v1/seller/seller/docid/1
content-type: application/json

{
  "fields": {
    "name": "bestseller",
    "address": {
      "lat": 1.0,
      "lng": 2.0
    }
  }
}

### add a product linked to the seller
POST http://localhost:8080/document/v1/product/product/docid/1
content-type: application/json

{
  "fields": {
    "title": "smart TV",
    "seller_ref": "id:seller:seller::1",
    "price": 100,
    "category": "electronics"
  }
}

### query for products by seller
POST http://localhost:8080/search/
content-type: application/json

{
  "yql": "select * from product where seller_name matches 'bestseller'"
}